sonar.projectKey=xpertgroup_prueba
sonar.projectName=xpertgroup_prueba
sonar.organization=bryanbarrera1996
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*Test.java,**/*Tests.java
sonar.java.binaries=target
sonar.exclusions=\
  terraform/**,\
  vars/**,\
  k8s_*.yaml,\
  **/*.sh,\
  **/*.rego,\
  zap_rules/**,\
  slack-emojis/**,\
  setup/**
sonar.coverage.exclusions=\
  **/*.sh,\
  **/*.yaml,\
  **/*.rego,\
  terraform/**
sonar.sourceEncoding=UTF-8