sonar.projectKey=xpertgroup_test
sonar.projectName=xpertgroup_test
sonar.organization=bryanbarrera1996
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.exclusions=\
  terraform/**,\
  vars/**,\
  k8s_*.yaml,\
  **/*.sh,\
  **/*.rego,\
  zap_rules/**,\
  slack-emojis/**,\
  setup/**

sonar.coverage.exclusions=\
  **/*.sh,\
  **/*.yaml,\
  **/*.rego,\
  terraform/**

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=github-actions:UseActionSha
sonar.issue.ignore.multicriteria.e1.resourceKey=.github/workflows/**