name: Deployment Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  static-analysis:
    name: Static Code Analysis (Sonar)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build & run tests (with coverage)
        run: mvn clean verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Sonar Quality Gate (fail if not compliant)
        uses: SonarSource/sonarcloud-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  terraform-plan:
    runs-on: ubuntu-latest
    needs: static-analysis  
    if: success()
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3,ec2,iam,sts
          DEBUG: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Wait for LocalStack
        run: |
          for i in {1..20}; do
            curl -sf http://localhost:4566/_localstack/health && exit 0
            sleep 5
          done
          exit 1

      - name: Terraform Init
        run: |
          cd terraform/environments/dev
          terraform init \
            -backend=false

      - name: Terraform Plan (LocalStack)
        run: |
          cd terraform/environments/dev
          terraform plan 